# Generated by Django 5.2.11 on 2026-03-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_vehicle_photo"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="reservation",
            table="reservation",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="accounts.vehicle",
            ),
        ),
    ]
