# Generated by Django 5.2.11 on 2026-03-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_reservation_table_and_vehicle_fk"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="maintenance",
            table="maintenance",
        ),
    ]
