# Generated by Django 5.2.11 on 2026-03-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_maintenance_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(blank=True, db_column='date_naissance', null=True),
        ),
        migrations.RenameField(
            model_name='client',
            old_name='date_naissance',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(db_column='prenom', max_length=100),
        ),
        migrations.RenameField(
            model_name='client',
            old_name='prenom',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(db_column='nom', max_length=100),
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(db_column='telephone', max_length=20),
        ),
        migrations.RenameField(
            model_name='client',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(db_column='fichier', upload_to='documents/'),
        ),
        migrations.RenameField(
            model_name='document',
            old_name='fichier',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='document',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True, db_column='date_upload'),
        ),
        migrations.RenameField(
            model_name='document',
            old_name='date_upload',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cout',
            field=models.DecimalField(db_column='cout', decimal_places=2, max_digits=10),
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='cout',
            new_name='cost',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.CharField(db_column='type', max_length=100),
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='type',
            new_name='maintenance_type',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='statut',
            field=models.CharField(db_column='statut', max_length=50),
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='statut',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, db_column='date_creation'),
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_fin',
            field=models.DateField(db_column='date_fin'),
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date_fin',
            new_name='end_date',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nombre_jour',
            field=models.IntegerField(db_column='nombre_jour'),
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='nombre_jour',
            new_name='number_of_days',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Etat_paiement',
            field=models.CharField(db_column='Etat_paiement', max_length=50),
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='Etat_paiement',
            new_name='payment_status',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_debut',
            field=models.DateField(db_column='date_debut'),
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date_debut',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(db_column='statut', max_length=50),
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='statut',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(db_column='prix_total', decimal_places=2, max_digits=10),
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='prix_total',
            new_name='total_price',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='marque',
            field=models.CharField(db_column='marque', max_length=100),
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='marque',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='categorie',
            field=models.CharField(db_column='categorie', max_length=100),
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='categorie',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='prix_par_jour',
            field=models.DecimalField(db_column='prix_par_jour', decimal_places=2, max_digits=10),
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='prix_par_jour',
            new_name='daily_price',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='carburantType',
            field=models.CharField(db_column='carburantType', max_length=50),
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='carburantType',
            new_name='fuel_type',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kilometrage',
            field=models.IntegerField(db_column='kilometrage'),
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='kilometrage',
            new_name='mileage',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='modele',
            field=models.CharField(db_column='modele', max_length=100),
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='modele',
            new_name='model',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='statut',
            field=models.CharField(db_column='statut', max_length=50),
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='statut',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='annee',
            field=models.IntegerField(db_column='annee'),
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='annee',
            new_name='year',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Payment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('amount', models.DecimalField(db_column='montant', decimal_places=2, max_digits=10)),
                        ('method', models.CharField(db_column='methode', max_length=50)),
                        ('payment_date', models.DateTimeField(auto_now_add=True, db_column='date_paiement')),
                        ('reference', models.CharField(max_length=100)),
                        ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.reservation')),
                    ],
                    options={
                        'db_table': 'accounts_paiement',
                    },
                ),
                migrations.DeleteModel(
                    name='Paiement',
                ),
            ],
            database_operations=[],
        ),
    ]
