# Generated by Django 5.2.11 on 2026-03-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_client_date_naissance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("Oil Change", "Oil Change"), ("Fuel", "Fuel"), ("Leasing", "Leasing"), ("Spare Parts", "Spare Parts"), ("Other", "Other")], max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("vehicle", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="expenses", to="accounts.vehicle")),
            ],
            options={
                "db_table": "expense",
            },
        ),
    ]
