# Generated by Django 5.2.11 on 2026-03-27 11:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_expense"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("method", models.CharField(choices=[("check", "Check"), ("cash", "Cash"), ("card_hold", "Card hold")], max_length=20)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("returned", "Returned"), ("cashed", "Cashed")], default="pending", max_length=20)),
                ("received_at", models.DateField(default=django.utils.timezone.localdate)),
                ("resolved_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("reservation", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="deposit", to="accounts.reservation")),
            ],
            options={
                "db_table": "deposit",
            },
        ),
    ]
